# Numeric STATUS variables representing what each status error message is
# refer to the STATUS array for the string name of each variable
STATUS_CLEAN_SHUTDOWN     = 1
STATUS_NO_SHUTDOWN        = 2
STATUS_NODES_REMAIN       = 3
STATUS_SERVERS_REMAIN     = 4
STATUS_CONNECTIONS_REMAIN = 5
STATUS_SPIDERS_REMAIN     = 6

STATUS = {
    STATUS_CLEAN_SHUTDOWN     : 'STATUS_CLEAN_SHUTDOWN',
    STATUS_NO_SHUTDOWN        : 'STATUS_NO_SHUTDOWN',
    STATUS_NODES_REMAIN       : 'STATUS_NODES_REMAIN',
    STATUS_SERVERS_REMAIN     : 'STATUS_SERVERS_REMAIN',
    STATUS_CONNECTIONS_REMAIN : 'STATUS_CONNECTIONS_REMAIN',
    STATUS_SPIDERS_REMAIN     : 'STATUS_SPIDERS_REMAIN'
}